import os
app_name = os.getenv("APP_NAME") 
app_env = os.getenv("APP_ENV") 
app_port = os.getenv("APP_PORT") 
app_server = os.getenv("APP_Server")
app_region = os.getenv("APP_REGION")
app_password = os.getenv("APP_PASSWORD")
app_host = os.getenv("APP_HOST")
print("Application:", app_name) 
print("Environment:", app_env) 
print("Port:", app_port) 
print("Server:", app_server)
print("Regiion:", app_region)
print("Password:", app_password)
print("Host:", app_host)